import copy
import json
import os

task_type_prompt = "Task type: time series classfication"


list_templates_by_chatgpt = [
    """<query>
以下时间序列是使用食品光谱仪对Robusta或者Aribica咖啡豆进行监测生成的数据。
时间序列：<ts-data-blank-sep>，其中数据点以空格分隔。
请判断该时间序列属于哪一种咖啡豆。
<options>
可能的类别包括：0,1。
请从上述选项中选择一个回答：
<response>
""",
     """<query>
以下时间序列是使用食品光谱仪对Robusta或者Aribica咖啡豆进行监测生成的数据。
时间序列：<ts-data-comma-sep>，其中数据点以逗号分隔。
请判断当前监测的是哪一种咖啡豆。
<options>
可能的类别包括：0,1。
请从上述选项中选择一个回答：
<response>
""",
    """<query>
时间序列：<ts-data-blank-sep>，其中数据点以空格分隔。
上述时间序列是使用食品光谱仪对Robusta或者Aribica咖啡豆进行监测生成的数据。
请判断该时间序列属于哪一种咖啡豆。
<options>
可能的类别包括：0,1。
请从上述选项中选择一个回答：
<response>
""",
    """<query>
The following time series are data generated by monitoring Robusta or Aribica coffee beans using a food spectrometer.
Time series: <ts-data-blank-sep>, where data points are separated by spaces.
Please determine which kind of coffee beans this time series belongs to.
<options>
Possible classes are: 0,1.
Please select an answer from the options above:
<response>
""",
    """<query>
The following time series are data generated by monitoring Robusta or Aribica coffee beans using a food spectrometer.
Time series: <ts-data-comma-sep>, where data points are separated by commas.
Please determine which coffee beans are currently being monitored.
<options>
Possible classes are: 0,1.
Please select an answer from the options above:
<response>
""",
    """<query>
Time series: <ts-data-blank-sep>, where data points are separated by spaces.
The above time series are data generated by monitoring Robusta or Aribica coffee beans using a food spectrometer.
Please determine which kind of coffee beans this time series belongs to.
<options>
Possible classes are: 0,1.
Please select an answer from the options above:
<response>
"""
]

label_map = {
    "0": "0",
    "1": "1",
}

label_map_zh = {
    "0": "0",
    "1": "1",
}


list_templates = []
list_templates.extend(list_templates_by_chatgpt)

task_name = "Coffee"
to_folder = os.path.join(
    "UCRArchive_2018/prompt_datasets/", f"{task_name}"
)
os.makedirs(to_folder, exist_ok=True)
for mode in ["TRAIN", "TEST"]:
    list_datas = []
    with open(f"UCRArchive_2018/{task_name}/{task_name}_{mode}.tsv", "r", encoding="utf-8") as f:
        for row in f:
            row = row.strip()
            if not row:
                continue

            label_ = row.split("\t")[0]
            label_name_ = label_map[label_]
            label_zh_name_ = label_map_zh[label_]

            ts_data_ = row.split("\t")[1: ]
            # assert len(ts_data_) == 96
            ts_data_blank_sep = " ".join(ts_data_)
            ts_data_comma_sep = ",".join(ts_data_)

            for template_ in list_templates:
                template_ = copy.copy(template_)

                # 确认数据怎么分割的
                if "comma-sep" in template_:
                    template_ = template_.replace(
                        "<ts-data-comma-sep>",
                        ts_data_comma_sep
                    )
                else:
                    template_ = template_.replace(
                        "<ts-data-blank-sep>",
                        ts_data_blank_sep
                    )

                # 确认中文还是英文
                target = ""
                if "序列" in template_:
                    target = label_zh_name_
                else:
                    target = label_name_

                list_datas.append(
                    {
                        "original_data": (label_name_, ts_data_blank_sep),
                        "target": target,
                        "input": template_,
                        "task_name": task_name,
                        "task_type": "classification",
                    }
                )

    print(f"len(list_datas): {len(list_datas)}")

    with open(os.path.join(to_folder, f"{mode}.json"), "w", encoding="utf-8") as f:
        for samp in list_datas:
            f.write(
                json.dumps(samp, ensure_ascii=False) + "\n"
            )


    